baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "灵兮澹忘"
theme = "maupassant"
googleAnalytics = "GA ID"
summaryLength = 140 

[author]
  name = "灵兮澹忘"

[params]
  busuanzi = true
  author = "灵兮澹忘"
  subtitle = "专注于Java、Python、数据分析等"
  keywords = "灵兮澹忘,java,博客,项目管理,python,数据分析,公众号,小程序"
  description = "专注于Java、Python、数据分析等"
  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file
  
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3


[params.utteranc]
    enable = true
    repo = ""    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种
  
	
